# Generated by Django 3.2.25 on 2024-06-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_app_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='app_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_app_images/'),
        ),
    ]
