# Generated by Django 5.0.6 on 2024-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appname", models.CharField(max_length=255)),
                ("appcategory", models.CharField(max_length=255)),
                ("applink", models.URLField()),
                ("points", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="app_images/")),
            ],
        ),
    ]
