# Generated by Django 3.2.25 on 2024-06-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='app_image',
            field=models.ImageField(blank=True, null=True, upload_to='app_images/'),
        ),
    ]
